url: "http://n.ethz.ch" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/~ncantieni" # the subpath of your site, e.g. /blog
title: "Nic Cantieni, ETHZ" # the name of your site, e.g. ACME Corp.
slide-prefix: ""