description: "Nic Cantieni's personal website at ETHZ."
author: "Nic Cantieni"
icon: '/assets/img/logo-n.png'
title-text:  " | Nic Cantieni | EEIT ETHZ"
footer-text: "Made with &#128420; in Graub&uuml;nda and Z&uuml;rich, CH."
twitter-card: "summary_large_image"
twitter-site: "@niccantieni"